spring:
  application:
    name: code-hackathon-app
  datasource:
    password: YkWFnbmBMsUsePLnaoqaqvJjMIVZVXsV
    url: postgresql://postgres:YkWFnbmBMsUsePLnaoqaqvJjMIVZVXsV@roundhouse.proxy.rlwy.net:18550/railway
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
