spring:
  application:
    name: code-hackathon-app
  datasource:
    password: YkWFnbmBMsUsePLnaoqaqvJjMIVZVXsV
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
